name = "sachron/clari_chain"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'sachron/clari_chain'"

[repository]
user = "sachron"
project = "clari_chain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[config.default]
network_id = 41
